/**
 * Crop-specific card decks for personalized farmer sessions.
 *
 * Strategy:
 * - Each crop has 6–8 cards covering all season phases
 * - When farmer selects crops, ONLY their crop cards + universal cards are used
 * - Universal cards = fraud, health, family, govt schemes (not crop-generic)
 */

// ─── Tags that mark cards as truly universal (not crop-specific) ───
export const UNIVERSAL_TAGS = [
  'fraud_call', 'digital_safety', 'health', 'savings', 'consumption',
  'planning', 'reflection', 'formal_credit', 'pm_kisan', 'ayushman',
  'migration', 'shock_expense',
]

// ─── WHEAT ────────────────────────────────────────────────────────
export const wheatCards = [
  {
    id: 'wheat_seed_selection',
    seasonPhase: 'pre_sowing',
    title: 'Wheat Seed Selection',
    title_hi: 'गेहूं बीज चुनाव',
    title_ta: 'கோதுமை விதை தேர்வு',
    prompt: 'HD-3086 (new variety) costs ₹55/kg, matures in 105 days and resists rust. PBW-343 (old variety) costs ₹30/kg and you have used it for years. Which do you plant?',
    prompt_hi: 'HD-3086 (नई किस्म) ₹55/किलो है, 105 दिनों में पकती है और रतुआ से बचाव करती है। PBW-343 (पुरानी किस्म) ₹30/किलो है और आप इसे सालों से उपयोग कर रहे हैं। कौन सी बोएंगे?',
    prompt_ta: 'HD-3086 (புதிய வகை) ₹55/கிலோ, 105 நாட்களில் முதிர்ந்து துரு எதிர்க்கும். PBW-343 (பழைய வகை) ₹30/கிலோ, பல ஆண்டுகளாக பயன்படுத்துகிறீர்கள். எதை விதைப்பீர்கள்?',
    left: { label: 'PBW-343 — familiar, cheaper', description: 'Known yield, lower input cost.' },
    right: { label: 'HD-3086 — new, rust-resistant', description: 'Higher cost but better disease protection.' },
    left_label_hi: 'PBW-343 — परिचित, सस्ता', left_desc_hi: 'जानी-पहचानी उपज, कम इनपुट लागत।',
    right_label_hi: 'HD-3086 — नया, रतुआ-प्रतिरोधी', right_desc_hi: 'अधिक लागत लेकिन बेहतर रोग सुरक्षा।',
    left_label_ta: 'PBW-343 — பரிச்சயமான, மலிவான', left_desc_ta: 'தெரிந்த மகசூல், குறைந்த உள்ளீடு செலவு.',
    right_label_ta: 'HD-3086 — புதிய, துரு-எதிர்ப்பு', right_desc_ta: 'அதிக செலவு ஆனால் சிறந்த நோய் பாதுகாப்பு.',
    effectsLeft:  { family: 0, crops: -5,  finance: 10, resilience: -10 },
    effectsRight: { family: 0, crops: 15,  finance: -8, resilience: 15  },
    narrator: 'elder',
    tags: ['wheat', 'seeds', 'pre_sowing'],
  },
  {
    id: 'wheat_sowing_timing',
    seasonPhase: 'sowing',
    title: 'Wheat Sowing Window',
    title_hi: 'गेहूं बुवाई का सही समय',
    title_ta: 'கோதுமை விதைப்பு சரியான நேரம்',
    prompt: 'Best sowing window for wheat is Nov 1–15. It is Nov 12 and your field is ready. But certified seeds arrive Nov 17. Sow now with local seeds or wait 5 days?',
    prompt_hi: 'गेहूं के लिए सबसे अच्छा बुवाई समय 1–15 नवंबर है। अभी 12 नवंबर है और आपका खेत तैयार है। लेकिन प्रमाणित बीज 17 नवंबर को आएंगे। अभी स्थानीय बीजों से बोएं या 5 दिन इंतज़ार करें?',
    prompt_ta: 'கோதுமைக்கு சிறந்த விதைப்பு நேரம் நவம்பர் 1–15. இப்போது நவம்பர் 12, வயல் தயார். ஆனால் சான்றிதழ் விதைகள் நவம்பர் 17 வரும். இப்போது உள்ளூர் விதைகளால் விதைக்கவா அல்லது 5 நாட்கள் காத்திருக்கவா?',
    left: { label: 'Sow now with local seeds', description: 'On time but germination uncertain.' },
    right: { label: 'Wait 5 days for certified seeds', description: 'Slight delay but guaranteed quality.' },
    left_label_hi: 'अभी स्थानीय बीजों से बोएं', left_desc_hi: 'समय पर लेकिन अंकुरण अनिश्चित।',
    right_label_hi: '5 दिन प्रमाणित बीजों का इंतज़ार करें', right_desc_hi: 'थोड़ी देरी लेकिन गुणवत्ता की गारंटी।',
    left_label_ta: 'இப்போது உள்ளூர் விதைகளால் விதை', left_desc_ta: 'சரியான நேரம் ஆனால் முளைப்பு நிச்சயமற்றது.',
    right_label_ta: '5 நாட்கள் சான்றிதழ் விதைகளுக்கு காத்திரு', right_desc_ta: 'சிறிய தாமதம் ஆனால் தரம் உத்தரவாதம்.',
    effectsLeft:  { family: 0, crops: -10, finance: 5,  resilience: -5 },
    effectsRight: { family: 0, crops: 15,  finance: -5, resilience: 10 },
    narrator: 'elder',
    tags: ['wheat', 'sowing'],
  },
  {
    id: 'wheat_fertilizer_dose',
    seasonPhase: 'sowing',
    title: 'Wheat Fertilizer Dose',
    title_hi: 'गेहूं उर्वरक मात्रा',
    title_ta: 'கோதுமை உர அளவு',
    prompt: 'Recommended dose for wheat is 120kg Urea + 60kg DAP per acre. A dealer offers a "bumper pack" with 50% extra urea at same price. More urea = more yield?',
    prompt_hi: 'गेहूं के लिए अनुशंसित मात्रा 120 किलो यूरिया + 60 किलो DAP प्रति एकड़ है। एक डीलर उसी कीमत पर 50% अतिरिक्त यूरिया के साथ "बंपर पैक" देता है। अधिक यूरिया = अधिक उपज?',
    prompt_ta: 'கோதுமைக்கு பரிந்துரைக்கப்பட்ட அளவு ஏக்கருக்கு 120கிலோ யூரியா + 60கிலோ DAP. ஒரு டீலர் அதே விலையில் 50% கூடுதல் யூரியாவுடன் "பம்பர் பேக்" தருகிறார். அதிக யூரியா = அதிக மகசூல்?',
    left: { label: 'Buy bumper pack, use extra urea', description: 'Seems like a deal but over-fertilizing burns roots.' },
    right: { label: 'Stick to recommended dose', description: 'Correct nutrition, healthy crop.' },
    left_label_hi: 'बंपर पैक खरीदें, अतिरिक्त यूरिया डालें', left_desc_hi: 'सौदा लगता है लेकिन अधिक खाद जड़ें जला देती है।',
    right_label_hi: 'अनुशंसित मात्रा पर टिके रहें', right_desc_hi: 'सही पोषण, स्वस्थ फसल।',
    left_label_ta: 'பம்பர் பேக் வாங்கு, கூடுதல் யூரியா போடு', left_desc_ta: 'சலுகை போல் தெரியும் ஆனால் அதிக உரம் வேர்களை எரிக்கும்.',
    right_label_ta: 'பரிந்துரைக்கப்பட்ட அளவில் தொடர்', right_desc_ta: 'சரியான ஊட்டம், ஆரோக்கியமான பயிர்.',
    effectsLeft:  { family: 0, crops: -15, finance: 5,  resilience: -10 },
    effectsRight: { family: 0, crops: 20,  finance: -8, resilience: 10  },
    narrator: 'bank_mitr',
    tags: ['wheat', 'fertilizer', 'sowing'],
  },
  {
    id: 'wheat_rust_attack',
    seasonPhase: 'growing',
    title: 'Yellow Rust on Wheat',
    title_hi: 'गेहूं पर पीला रतुआ',
    title_ta: 'கோதுமையில் மஞ்சள் துரு',
    prompt: 'Yellow rust spots appear on your wheat leaves in January. Fungicide spray costs ₹1,200/acre. If untreated, rust can destroy 40% of yield. Your neighbour says it will pass.',
    prompt_hi: 'जनवरी में आपकी गेहूं की पत्तियों पर पीले रतुआ के धब्बे दिखते हैं। फफूंदनाशक स्प्रे ₹1,200/एकड़ है। अगर इलाज न हो तो रतुआ 40% उपज नष्ट कर सकता है। पड़ोसी कहता है ठीक हो जाएगा।',
    prompt_ta: 'ஜனவரியில் கோதுமை இலைகளில் மஞ்சள் துரு புள்ளிகள். பூஞ்சைக்கொல்லி ₹1,200/ஏக்கர். சிகிச்சை இல்லாவிட்டால் 40% மகசூல் அழியலாம். அண்டை வீட்டார் சரியாகும் என்கிறார்.',
    left: { label: 'Skip spray, hope it passes', description: 'Save ₹1,200 but risk 40% yield loss.' },
    right: { label: 'Spray fungicide immediately', description: 'Spend now, protect the full harvest.' },
    left_label_hi: 'स्प्रे छोड़ें, उम्मीद करें ठीक हो जाए', left_desc_hi: '₹1,200 बचाएं लेकिन 40% उपज हानि का जोखिम।',
    right_label_hi: 'तुरंत फफूंदनाशक स्प्रे करें', right_desc_hi: 'अभी खर्च करें, पूरी फसल बचाएं।',
    left_label_ta: 'தெளிப்பு தவிர், சரியாகும் என நம்பு', left_desc_ta: '₹1,200 சேமி ஆனால் 40% மகசூல் இழப்பு ஆபத்து.',
    right_label_ta: 'உடனே பூஞ்சைக்கொல்லி தெளி', right_desc_ta: 'இப்போது செலவழி, முழு அறுவடையை காப்பாற்று.',
    effectsLeft:  { family: 0, crops: -25, finance: 5,   resilience: -10 },
    effectsRight: { family: 0, crops: 15,  finance: -10, resilience: 10  },
    narrator: 'elder',
    tags: ['wheat', 'pest', 'growing'],
  },
  {
    id: 'wheat_irrigation_schedule',
    seasonPhase: 'growing',
    title: 'Wheat Irrigation Timing',
    title_hi: 'गेहूं सिंचाई का समय',
    title_ta: 'கோதுமை நீர்ப்பாசன நேரம்',
    prompt: 'Wheat needs 5–6 irrigations. The critical one is at Crown Root Initiation (CRI) stage — 21 days after sowing. You are busy with a family function. Skip CRI irrigation or delay the function?',
    prompt_hi: 'गेहूं को 5–6 सिंचाई चाहिए। सबसे महत्वपूर्ण CRI (क्राउन रूट इनिशिएशन) चरण पर है — बुवाई के 21 दिन बाद। आप एक पारिवारिक समारोह में व्यस्त हैं। CRI सिंचाई छोड़ें या समारोह टालें?',
    prompt_ta: 'கோதுமைக்கு 5–6 நீர்ப்பாசனம் தேவை. முக்கியமானது CRI நிலையில் — விதைத்த 21 நாட்கள் பிறகு. குடும்ப நிகழ்ச்சியில் பிஸியாக இருக்கிறீர்கள். CRI நீர்ப்பாசனம் தவிர்க்கவா அல்லது நிகழ்ச்சியை தள்ளிவைக்கவா?',
    left: { label: 'Skip CRI irrigation, attend function', description: 'Family first, but crop suffers at critical stage.' },
    right: { label: 'Irrigate first, delay function', description: 'Crop protected, family slightly inconvenienced.' },
    left_label_hi: 'CRI सिंचाई छोड़ें, समारोह में जाएं', left_desc_hi: 'परिवार पहले, लेकिन फसल महत्वपूर्ण चरण में प्रभावित।',
    right_label_hi: 'पहले सिंचाई करें, समारोह टालें', right_desc_hi: 'फसल सुरक्षित, परिवार थोड़ा असुविधाजनक।',
    left_label_ta: 'CRI நீர்ப்பாசனம் தவிர், நிகழ்ச்சிக்கு செல்', left_desc_ta: 'குடும்பம் முதல், ஆனால் முக்கிய நிலையில் பயிர் பாதிக்கும்.',
    right_label_ta: 'முதலில் நீர்ப்பாசனம், நிகழ்ச்சி தள்ளிவை', right_desc_ta: 'பயிர் பாதுகாப்பு, குடும்பம் சிறிது சிரமம்.',
    effectsLeft:  { family: 10, crops: -20, finance: 0,  resilience: -10 },
    effectsRight: { family: -5, crops: 20,  finance: 0,  resilience: 10  },
    narrator: 'self',
    tags: ['wheat', 'irrigation', 'growing'],
  },
  {
    id: 'wheat_msp_vs_trader',
    seasonPhase: 'harvest',
    title: 'Wheat: MSP or Trader?',
    title_hi: 'गेहूं: MSP या व्यापारी?',
    title_ta: 'கோதுமை: MSP அல்லது வியாபாரி?',
    prompt: 'Government MSP for wheat is ₹2,275/quintal, procurement starts next week. A private trader offers ₹2,100 today and will collect from your field — saving transport cost.',
    prompt_hi: 'गेहूं का सरकारी MSP ₹2,275/क्विंटल है, खरीद अगले हफ्ते शुरू होती है। एक निजी व्यापारी आज ₹2,100 देता है और आपके खेत से उठाएगा — परिवहन लागत बचेगी।',
    prompt_ta: 'கோதுமை அரசு MSP ₹2,275/குவிண்டால், கொள்முதல் அடுத்த வாரம். தனியார் வியாபாரி இன்று ₹2,100 தருகிறார், வயலிலிருந்தே எடுப்பார் — போக்குவரத்து மிச்சம்.',
    left: { label: 'Sell to trader today', description: 'Less per quintal but zero transport hassle.' },
    right: { label: 'Wait for MSP procurement', description: '₹175 more per quintal, you arrange transport.' },
    left_label_hi: 'आज व्यापारी को बेचें', left_desc_hi: 'प्रति क्विंटल कम लेकिन परिवहन झंझट नहीं।',
    right_label_hi: 'MSP खरीद का इंतज़ार करें', right_desc_hi: 'प्रति क्विंटल ₹175 अधिक, परिवहन आपको करना होगा।',
    left_label_ta: 'இன்று வியாபாரிக்கு விற்று', left_desc_ta: 'குவிண்டாலுக்கு குறைவு ஆனால் போக்குவரத்து சிக்கல் இல்லை.',
    right_label_ta: 'MSP கொள்முதலுக்கு காத்திரு', right_desc_ta: 'குவிண்டாலுக்கு ₹175 அதிகம், போக்குவரத்து நீங்களே.',
    effectsLeft:  { family: 0, crops: 0, finance: -10, resilience: -5 },
    effectsRight: { family: 0, crops: 0, finance: 20,  resilience: 10 },
    narrator: 'bank_mitr',
    tags: ['wheat', 'msp', 'harvest'],
  },
  {
    id: 'wheat_combine_hire',
    seasonPhase: 'harvest',
    title: 'Combine Harvester Booking',
    title_hi: 'कंबाइन हार्वेस्टर बुकिंग',
    title_ta: 'கம்பைன் அறுவடை இயந்திர முன்பதிவு',
    prompt: 'Wheat is ready to harvest. Combine harvester costs ₹1,200/acre but is booked for 10 days. Manual harvesting costs ₹3,500/acre but can start tomorrow. Delay risks grain shattering.',
    prompt_hi: 'गेहूं कटाई के लिए तैयार है। कंबाइन हार्वेस्टर ₹1,200/एकड़ है लेकिन 10 दिनों के लिए बुक है। मैनुअल कटाई ₹3,500/एकड़ है लेकिन कल शुरू हो सकती है। देरी से दाने झड़ने का खतरा।',
    prompt_ta: 'கோதுமை அறுவடைக்கு தயார். கம்பைன் ₹1,200/ஏக்கர் ஆனால் 10 நாட்களுக்கு முன்பதிவு. கைமுறை அறுவடை ₹3,500/ஏக்கர் ஆனால் நாளை தொடங்கலாம். தாமதம் தானியம் உதிரும் ஆபத்து.',
    left: { label: 'Wait 10 days for combine', description: 'Cheaper but risk of grain loss from delay.' },
    right: { label: 'Manual harvest tomorrow', description: 'Costlier but no delay, no grain loss.' },
    left_label_hi: 'कंबाइन के लिए 10 दिन इंतज़ार करें', left_desc_hi: 'सस्ता लेकिन देरी से दाने झड़ने का जोखिम।',
    right_label_hi: 'कल मैनुअल कटाई करें', right_desc_hi: 'महंगा लेकिन देरी नहीं, दाने नहीं झड़ेंगे।',
    left_label_ta: 'கம்பைனுக்கு 10 நாட்கள் காத்திரு', left_desc_ta: 'மலிவானது ஆனால் தாமதத்தால் தானியம் உதிரும் ஆபத்து.',
    right_label_ta: 'நாளை கைமுறை அறுவடை', right_desc_ta: 'விலை அதிகம் ஆனால் தாமதம் இல்லை, தானியம் உதிராது.',
    effectsLeft:  { family: 0, crops: -15, finance: 10, resilience: -5  },
    effectsRight: { family: 0, crops: 10,  finance: -15, resilience: 10 },
    narrator: 'self',
    tags: ['wheat', 'harvest', 'mechanisation'],
  },
  {
    id: 'wheat_straw_management',
    seasonPhase: 'off_season',
    title: 'Wheat Stubble Burning',
    title_hi: 'गेहूं पराली जलाना',
    title_ta: 'கோதுமை தாள் எரிப்பு',
    prompt: 'After wheat harvest, stubble remains. Burning it clears the field in 1 day for free. But it is illegal and harms soil. A happy seeder machine can sow paddy directly into stubble for ₹1,500/acre.',
    prompt_hi: 'गेहूं की कटाई के बाद पराली बचती है। इसे जलाने से 1 दिन में खेत मुफ्त में साफ हो जाता है। लेकिन यह अवैध है और मिट्टी को नुकसान पहुंचाता है। हैप्पी सीडर मशीन पराली में सीधे धान बो सकती है ₹1,500/एकड़ में।',
    prompt_ta: 'கோதுமை அறுவடைக்கு பிறகு தாள் மிஞ்சும். எரிப்பது 1 நாளில் இலவசமாக வயல் சுத்தம் செய்யும். ஆனால் சட்டவிரோதம், மண்ணை பாதிக்கும். ஹேப்பி சீடர் இயந்திரம் தாளில் நேரடியாக நெல் விதைக்கலாம் ₹1,500/ஏக்கர்.',
    left: { label: 'Burn stubble — fast and free', description: 'Illegal, harms soil, causes air pollution.' },
    right: { label: 'Use happy seeder, protect soil', description: 'Costs ₹1,500 but legal and soil-healthy.' },
    left_label_hi: 'पराली जलाएं — तेज़ और मुफ्त', left_desc_hi: 'अवैध, मिट्टी को नुकसान, वायु प्रदूषण।',
    right_label_hi: 'हैप्पी सीडर उपयोग करें, मिट्टी बचाएं', right_desc_hi: '₹1,500 लागत लेकिन कानूनी और मिट्टी के लिए स्वस्थ।',
    left_label_ta: 'தாள் எரி — வேகமான மற்றும் இலவசம்', left_desc_ta: 'சட்டவிரோதம், மண் பாதிப்பு, காற்று மாசு.',
    right_label_ta: 'ஹேப்பி சீடர் பயன்படுத்து, மண் காப்பாற்று', right_desc_ta: '₹1,500 செலவு ஆனால் சட்டப்பூர்வம், மண் ஆரோக்கியம்.',
    effectsLeft:  { family: 0, crops: -20, finance: 10, resilience: -20 },
    effectsRight: { family: 0, crops: 10,  finance: -8, resilience: 20  },
    narrator: 'bank_mitr',
    tags: ['wheat', 'stubble', 'off_season', 'environment'],
  },
]

// ─── PADDY ────────────────────────────────────────────────────────
export const paddyCards = [
  {
    id: 'paddy_nursery_prep',
    seasonPhase: 'pre_sowing',
    title: 'Paddy Nursery Preparation',
    title_hi: 'धान नर्सरी तैयारी',
    title_ta: 'நெல் நாற்றங்கால் தயாரிப்பு',
    prompt: 'You need to prepare a paddy nursery 25–30 days before transplanting. Wet nursery (traditional) needs more water. Dry nursery saves water but needs careful management. Which method?',
    prompt_hi: 'रोपाई से 25–30 दिन पहले धान की नर्सरी तैयार करनी होगी। गीली नर्सरी (पारंपरिक) को अधिक पानी चाहिए। सूखी नर्सरी पानी बचाती है लेकिन सावधानीपूर्वक प्रबंधन चाहिए।',
    prompt_ta: 'நடவுக்கு 25–30 நாட்கள் முன் நெல் நாற்றங்கால் தயார் செய்ய வேண்டும். ஈர நாற்றங்கால் (பாரம்பரிய) அதிக நீர் தேவை. உலர் நாற்றங்கால் நீர் சேமிக்கும் ஆனால் கவனமான மேலாண்மை தேவை.',
    left: { label: 'Wet nursery — familiar method', description: 'More water use but you know it well.' },
    right: { label: 'Dry nursery — save water', description: 'Less water, needs careful attention.' },
    left_label_hi: 'गीली नर्सरी — परिचित तरीका', left_desc_hi: 'अधिक पानी लेकिन आप इसे अच्छी तरह जानते हैं।',
    right_label_hi: 'सूखी नर्सरी — पानी बचाएं', right_desc_hi: 'कम पानी, सावधानीपूर्वक ध्यान चाहिए।',
    left_label_ta: 'ஈர நாற்றங்கால் — பரிச்சயமான முறை', left_desc_ta: 'அதிக நீர் ஆனால் நன்கு தெரியும்.',
    right_label_ta: 'உலர் நாற்றங்கால் — நீர் சேமி', right_desc_ta: 'குறைந்த நீர், கவனமான கவனிப்பு தேவை.',
    effectsLeft:  { family: 0, crops: 5,  finance: -5,  resilience: -10 },
    effectsRight: { family: 0, crops: 10, finance: 5,   resilience: 15  },
    narrator: 'elder',
    tags: ['paddy', 'nursery', 'pre_sowing'],
  },
  {
    id: 'paddy_transplant_labour',
    seasonPhase: 'sowing',
    title: 'Paddy Transplanting: Labour vs Machine',
    title_hi: 'धान रोपाई: मज़दूर बनाम मशीन',
    title_ta: 'நெல் நடவு: தொழிலாளர் vs இயந்திரம்',
    prompt: 'Transplanting 2 acres of paddy needs 8 labourers × 3 days at ₹500/day = ₹12,000. A transplanting machine rental costs ₹3,500 for the whole field and finishes in 1 day.',
    prompt_hi: '2 एकड़ धान की रोपाई के लिए 8 मज़दूर × 3 दिन × ₹500/दिन = ₹12,000 चाहिए। ट्रांसप्लांटिंग मशीन किराया पूरे खेत के लिए ₹3,500 है और 1 दिन में खत्म होती है।',
    prompt_ta: '2 ஏக்கர் நெல் நடவுக்கு 8 தொழிலாளர் × 3 நாட்கள் × ₹500/நாள் = ₹12,000. நடவு இயந்திர வாடகை முழு வயலுக்கும் ₹3,500, 1 நாளில் முடியும்.',
    left: { label: 'Hire labourers — ₹12,000', description: 'Traditional, supports local workers.' },
    right: { label: 'Rent machine — ₹3,500', description: 'Saves ₹8,500 and finishes faster.' },
    left_label_hi: 'मज़दूर काम पर लें — ₹12,000', left_desc_hi: 'पारंपरिक, स्थानीय मज़दूरों को सहायता।',
    right_label_hi: 'मशीन किराए पर लें — ₹3,500', right_desc_hi: '₹8,500 बचाएं और जल्दी खत्म करें।',
    left_label_ta: 'தொழிலாளர் அமர்த்து — ₹12,000', left_desc_ta: 'பாரம்பரிய, உள்ளூர் தொழிலாளர்களுக்கு ஆதரவு.',
    right_label_ta: 'இயந்திரம் வாடகை — ₹3,500', right_desc_ta: '₹8,500 சேமிப்பு, வேகமாக முடியும்.',
    effectsLeft:  { family: 10, crops: 5,  finance: -20, resilience: -5 },
    effectsRight: { family: 0,  crops: 15, finance: 15,  resilience: 10 },
    narrator: 'self',
    tags: ['paddy', 'labour', 'sowing'],
  },
  {
    id: 'paddy_water_management',
    seasonPhase: 'growing',
    title: 'Paddy Water Management',
    title_hi: 'धान जल प्रबंधन',
    title_ta: 'நெல் நீர் மேலாண்மை',
    prompt: 'Continuous flooding uses 1,200mm water per season. AWD (Alternate Wetting and Drying) technique saves 30% water with no yield loss. But it needs a field water tube to monitor levels.',
    prompt_hi: 'लगातार बाढ़ से प्रति सीज़न 1,200 मिमी पानी लगता है। AWD (वैकल्पिक गीला और सुखाना) तकनीक बिना उपज हानि के 30% पानी बचाती है। लेकिन इसके लिए स्तर मापने के लिए फील्ड वाटर ट्यूब चाहिए।',
    prompt_ta: 'தொடர்ச்சியான வெள்ளம் சீசனுக்கு 1,200மிமீ நீர் பயன்படுத்தும். AWD (மாற்றி ஈரமாக்கல் மற்றும் உலர்த்தல்) நுட்பம் மகசூல் இழப்பின்றி 30% நீர் சேமிக்கும். ஆனால் அளவு கண்காணிக்க ஃபீல்ட் வாட்டர் டியூப் தேவை.',
    left: { label: 'Continue flood irrigation', description: 'Familiar but wastes water and money.' },
    right: { label: 'Try AWD technique', description: 'Save 30% water cost, same yield.' },
    left_label_hi: 'बाढ़ सिंचाई जारी रखें', left_desc_hi: 'परिचित लेकिन पानी और पैसे बर्बाद।',
    right_label_hi: 'AWD तकनीक आज़माएं', right_desc_hi: '30% पानी लागत बचाएं, वही उपज।',
    left_label_ta: 'வெள்ள நீர்ப்பாசனம் தொடர்', left_desc_ta: 'பரிச்சயமான ஆனால் நீர் மற்றும் பணம் வீணாகும்.',
    right_label_ta: 'AWD நுட்பம் முயற்சி செய்', right_desc_ta: '30% நீர் செலவு சேமிப்பு, அதே மகசூல்.',
    effectsLeft:  { family: 0, crops: 5,  finance: -15, resilience: -15 },
    effectsRight: { family: 0, crops: 10, finance: 10,  resilience: 20  },
    narrator: 'bank_mitr',
    tags: ['paddy', 'water', 'growing'],
  },
  {
    id: 'paddy_blast_disease',
    seasonPhase: 'growing',
    title: 'Paddy Blast Disease',
    title_hi: 'धान ब्लास्ट रोग',
    title_ta: 'நெல் ப்ளாஸ்ட் நோய்',
    prompt: 'You notice diamond-shaped lesions on paddy leaves — classic blast disease. It spreads fast in humid weather. Tricyclazole spray costs ₹900/acre. Delay risks 50% crop loss.',
    prompt_hi: 'आपको धान की पत्तियों पर हीरे के आकार के धब्बे दिखते हैं — क्लासिक ब्लास्ट रोग। यह नम मौसम में तेज़ी से फैलता है। ट्राइसाइक्लाज़ोल स्प्रे ₹900/एकड़ है। देरी से 50% फसल हानि का जोखिम।',
    prompt_ta: 'நெல் இலைகளில் வைர வடிவ புண்கள் — கிளாசிக் ப்ளாஸ்ட் நோய். ஈரமான வானிலையில் வேகமாக பரவும். ட்ரைசைக்லாசோல் தெளிப்பு ₹900/ஏக்கர். தாமதம் 50% பயிர் இழப்பு ஆபத்து.',
    left: { label: 'Wait 2 days, monitor closely', description: 'Risk rapid spread in humid conditions.' },
    right: { label: 'Spray Tricyclazole today', description: '₹900 now saves the entire crop.' },
    left_label_hi: '2 दिन इंतज़ार करें, ध्यान से देखें', left_desc_hi: 'नम परिस्थितियों में तेज़ फैलाव का जोखिम।',
    right_label_hi: 'आज ट्राइसाइक्लाज़ोल स्प्रे करें', right_desc_hi: '₹900 अभी पूरी फसल बचाता है।',
    left_label_ta: '2 நாட்கள் காத்திரு, கவனமாக கண்காணி', left_desc_ta: 'ஈரமான சூழலில் வேகமான பரவல் ஆபத்து.',
    right_label_ta: 'இன்று ட்ரைசைக்லாசோல் தெளி', right_desc_ta: '₹900 இப்போது முழு பயிரை காப்பாற்றும்.',
    effectsLeft:  { family: 0, crops: -30, finance: 5,   resilience: -15 },
    effectsRight: { family: 0, crops: 20,  finance: -8,  resilience: 15  },
    narrator: 'elder',
    tags: ['paddy', 'disease', 'growing'],
  },
  {
    id: 'paddy_water_shortage',
    seasonPhase: 'growing',
    title: 'Canal Water Cut for 10 Days',
    title_hi: 'नहर का पानी 10 दिन बंद',
    title_ta: 'கால்வாய் நீர் 10 நாட்கள் நிறுத்தம்',
    prompt: 'Canal water is cut for 10 days due to upstream repairs. Paddy needs water every 3–4 days. Groundwater pumping costs ₹800/day. Skip irrigation and risk 20% yield loss.',
    prompt_hi: 'ऊपरी मरम्मत के कारण नहर का पानी 10 दिनों के लिए बंद है। धान को हर 3–4 दिन में पानी चाहिए। भूजल पंपिंग ₹800/दिन है। सिंचाई छोड़ें और 20% उपज हानि का जोखिम उठाएं।',
    prompt_ta: 'மேல்நிலை பழுதுபார்ப்பால் கால்வாய் நீர் 10 நாட்கள் நிறுத்தம். நெல்லுக்கு ஒவ்வொரு 3–4 நாட்களுக்கும் நீர் தேவை. நிலத்தடி நீர் பம்பிங் ₹800/நாள். நீர்ப்பாசனம் தவிர்த்து 20% மகசூல் இழப்பு ஆபத்து.',
    left: { label: 'Skip irrigation, save ₹8,000', description: 'Risk 20% yield loss.' },
    right: { label: 'Pump groundwater for 10 days', description: 'Spend ₹8,000 to protect full yield.' },
    left_label_hi: 'सिंचाई छोड़ें, ₹8,000 बचाएं', left_desc_hi: '20% उपज हानि का जोखिम।',
    right_label_hi: '10 दिन भूजल पंप करें', right_desc_hi: 'पूरी उपज बचाने के लिए ₹8,000 खर्च करें।',
    left_label_ta: 'நீர்ப்பாசனம் தவிர், ₹8,000 சேமி', left_desc_ta: '20% மகசூல் இழப்பு ஆபத்து.',
    right_label_ta: '10 நாட்கள் நிலத்தடி நீர் பம்ப் செய்', right_desc_ta: 'முழு மகசூல் காக்க ₹8,000 செலவழி.',
    effectsLeft:  { family: 0, crops: -20, finance: 10,  resilience: -10 },
    effectsRight: { family: 0, crops: 15,  finance: -15, resilience: 10  },
    narrator: 'self',
    tags: ['paddy', 'water', 'growing'],
  },
  {
    id: 'paddy_msp_procurement',
    seasonPhase: 'harvest',
    title: 'Paddy MSP — Register or Agent?',
    title_hi: 'धान MSP — खुद पंजीकरण या एजेंट?',
    title_ta: 'நெல் MSP — நீங்களே பதிவா அல்லது முகவரா?',
    prompt: 'Paddy MSP is ₹2,183/quintal. Government procurement starts in 2 weeks — you must register online. A local agent offers to register for ₹500 "service fee". CSC centre is 3km away.',
    prompt_hi: 'धान MSP ₹2,183/क्विंटल है। सरकारी खरीद 2 हफ्ते में शुरू होती है — आपको ऑनलाइन पंजीकरण करना होगा। एक स्थानीय एजेंट ₹500 "सेवा शुल्क" पर पंजीकरण करने की पेशकश करता है। CSC केंद्र 3 किमी दूर है।',
    prompt_ta: 'நெல் MSP ₹2,183/குவிண்டால். அரசு கொள்முதல் 2 வாரங்களில் — ஆன்லைனில் பதிவு செய்ய வேண்டும். உள்ளூர் முகவர் ₹500 "சேவை கட்டணம்" பெற்று பதிவு செய்ய வழங்குகிறார். CSC மையம் 3கிமீ தூரம்.',
    left: { label: 'Pay agent ₹500 to register', description: 'Convenient but unnecessary cost.' },
    right: { label: 'Go to CSC, register free', description: '3km trip but saves ₹500, learn the process.' },
    left_label_hi: 'एजेंट को ₹500 दें', left_desc_hi: 'सुविधाजनक लेकिन अनावश्यक लागत।',
    right_label_hi: 'CSC जाएं, मुफ्त पंजीकरण करें', right_desc_hi: '3 किमी यात्रा लेकिन ₹500 बचाएं, प्रक्रिया सीखें।',
    left_label_ta: 'முகவருக்கு ₹500 கொடு', left_desc_ta: 'வசதியானது ஆனால் தேவையற்ற செலவு.',
    right_label_ta: 'CSC செல், இலவசமாக பதிவு செய்', right_desc_ta: '3கிமீ பயணம் ஆனால் ₹500 சேமிப்பு, செயல்முறை கற்றுக்கொள்.',
    effectsLeft:  { family: 0, crops: 0, finance: -5,  resilience: -5  },
    effectsRight: { family: 5, crops: 0, finance: 20,  resilience: 15  },
    narrator: 'bank_mitr',
    tags: ['paddy', 'msp', 'harvest'],
  },
  {
    id: 'paddy_parboiling',
    seasonPhase: 'harvest',
    title: 'Parboiled vs Raw Rice',
    title_hi: 'उसना चावल बनाम कच्चा चावल',
    title_ta: 'வேகவைத்த அரிசி vs பச்சை அரிசி',
    prompt: 'A rice miller offers ₹200 more per quintal for parboiled paddy. Parboiling takes 2 extra days and ₹300/quintal processing cost. Is it worth it?',
    prompt_hi: 'एक चावल मिलर उसना धान के लिए ₹200 प्रति क्विंटल अधिक देता है। उसना बनाने में 2 अतिरिक्त दिन और ₹300/क्विंटल प्रसंस्करण लागत लगती है। क्या यह फायदेमंद है?',
    prompt_ta: 'ஒரு அரிசி மில்லர் வேகவைத்த நெல்லுக்கு குவிண்டாலுக்கு ₹200 அதிகம் தருகிறார். வேகவைக்க 2 கூடுதல் நாட்கள் மற்றும் ₹300/குவிண்டால் செயலாக்க செலவு. மதிப்புள்ளதா?',
    left: { label: 'Sell raw paddy immediately', description: 'Less price but no extra effort.' },
    right: { label: 'Parboil and sell at premium', description: '₹200 more per quintal minus ₹300 cost = net loss. Think carefully.' },
    left_label_hi: 'तुरंत कच्चा धान बेचें', left_desc_hi: 'कम कीमत लेकिन अतिरिक्त मेहनत नहीं।',
    right_label_hi: 'उसना बनाएं और प्रीमियम पर बेचें', right_desc_hi: '₹200 अधिक प्रति क्विंटल लेकिन ₹300 लागत = शुद्ध हानि। सोचें।',
    left_label_ta: 'உடனே பச்சை நெல் விற்று', left_desc_ta: 'குறைந்த விலை ஆனால் கூடுதல் முயற்சி இல்லை.',
    right_label_ta: 'வேகவைத்து பிரீமியத்தில் விற்று', right_desc_ta: 'குவிண்டாலுக்கு ₹200 அதிகம் ஆனால் ₹300 செலவு = நிகர இழப்பு. யோசி.',
    effectsLeft:  { family: 0, crops: 0,  finance: 10, resilience: 5   },
    effectsRight: { family: 0, crops: 5,  finance: -5, resilience: -5  },
    narrator: 'self',
    tags: ['paddy', 'value_addition', 'harvest'],
  },
]

// ─── SUGARCANE ────────────────────────────────────────────────────
export const sugarcaneCards = [
  {
    id: 'sugarcane_variety',
    seasonPhase: 'pre_sowing',
    title: 'Sugarcane Variety Choice',
    title_hi: 'गन्ना किस्म चुनाव',
    title_ta: 'கரும்பு வகை தேர்வு',
    prompt: 'Co-0238 (early variety) matures in 10 months, gives 85 tonnes/acre, and is preferred by mills. Co-86032 (late variety) matures in 14 months but gives 100 tonnes/acre. Which to plant?',
    prompt_hi: 'Co-0238 (अगेती किस्म) 10 महीने में पकती है, 85 टन/एकड़ देती है और मिलों को पसंद है। Co-86032 (पछेती किस्म) 14 महीने में पकती है लेकिन 100 टन/एकड़ देती है। कौन सी लगाएं?',
    prompt_ta: 'Co-0238 (ஆரம்ப வகை) 10 மாதங்களில் முதிர்ந்து 85 டன்/ஏக்கர் தரும், ஆலைகளுக்கு விருப்பம். Co-86032 (தாமத வகை) 14 மாதங்களில் முதிர்ந்து 100 டன்/ஏக்கர் தரும். எதை நடவு செய்வீர்கள்?',
    left: { label: 'Co-0238 — early, mill-preferred', description: '10 months, 85 tonnes, faster cash.' },
    right: { label: 'Co-86032 — late, higher yield', description: '14 months wait but 18% more yield.' },
    left_label_hi: 'Co-0238 — अगेती, मिल-पसंदीदा', left_desc_hi: '10 महीने, 85 टन, जल्दी नकद।',
    right_label_hi: 'Co-86032 — पछेती, अधिक उपज', right_desc_hi: '14 महीने इंतज़ार लेकिन 18% अधिक उपज।',
    left_label_ta: 'Co-0238 — ஆரம்ப, ஆலை-விருப்பம்', left_desc_ta: '10 மாதங்கள், 85 டன், வேகமான பணம்.',
    right_label_ta: 'Co-86032 — தாமத, அதிக மகசூல்', right_desc_ta: '14 மாதங்கள் காத்திருப்பு ஆனால் 18% அதிக மகசூல்.',
    effectsLeft:  { family: 5,  crops: 5,  finance: 10, resilience: 5  },
    effectsRight: { family: -5, crops: 20, finance: -5, resilience: 10 },
    narrator: 'elder',
    tags: ['sugarcane', 'variety', 'pre_sowing'],
  },
  {
    id: 'sugarcane_ratoon',
    seasonPhase: 'pre_sowing',
    title: 'Ratoon or Replant?',
    title_hi: 'रैटून या नई रोपाई?',
    title_ta: 'ராட்டூன் அல்லது புதிய நடவு?',
    prompt: 'After harvest, you can grow a ratoon crop from the same roots — saves ₹8,000 replanting cost but yields 20% less. Or replant fresh setts for full yield next year.',
    prompt_hi: 'कटाई के बाद, उन्हीं जड़ों से रैटून फसल उगा सकते हैं — ₹8,000 रोपाई लागत बचती है लेकिन उपज 20% कम होती है। या अगले साल पूरी उपज के लिए नए सेट्स से रोपाई करें।',
    prompt_ta: 'அறுவடைக்கு பிறகு, அதே வேர்களிலிருந்து ராட்டூன் பயிர் வளர்க்கலாம் — ₹8,000 நடவு செலவு மிச்சம் ஆனால் மகசூல் 20% குறைவு. அல்லது அடுத்த ஆண்டு முழு மகசூலுக்கு புதிய செட்ஸ் நடவு செய்யலாம்.',
    left: { label: 'Grow ratoon — save ₹8,000', description: 'Lower yield but saves replanting cost.' },
    right: { label: 'Replant fresh for full yield', description: 'Higher cost but maximum next harvest.' },
    left_label_hi: 'रैटून उगाएं — ₹8,000 बचाएं', left_desc_hi: 'कम उपज लेकिन रोपाई लागत बचत।',
    right_label_hi: 'पूरी उपज के लिए नई रोपाई', right_desc_hi: 'अधिक लागत लेकिन अधिकतम अगली फसल।',
    left_label_ta: 'ராட்டூன் வளர் — ₹8,000 சேமி', left_desc_ta: 'குறைந்த மகசூல் ஆனால் நடவு செலவு சேமிப்பு.',
    right_label_ta: 'முழு மகசூலுக்கு புதிய நடவு', right_desc_ta: 'அதிக செலவு ஆனால் அதிகபட்ச அடுத்த அறுவடை.',
    effectsLeft:  { family: 0, crops: -10, finance: 15, resilience: 5  },
    effectsRight: { family: 0, crops: 20,  finance: -10, resilience: 10 },
    narrator: 'elder',
    tags: ['sugarcane', 'ratoon', 'pre_sowing'],
  },
  {
    id: 'sugarcane_long_cycle_cash',
    seasonPhase: 'sowing',
    title: 'Sugarcane: 12-Month Cash Gap',
    title_hi: 'गन्ना: 12 महीने का नकद अंतर',
    title_ta: 'கரும்பு: 12 மாத பண இடைவெளி',
    prompt: 'Sugarcane takes 12 months to harvest. You have savings for only 6 months of household expenses. Take a short-term loan now or cut family expenses for 6 months?',
    prompt_hi: 'गन्ने की फसल 12 महीने में तैयार होती है। आपके पास केवल 6 महीने के घरेलू खर्च के लिए बचत है। अभी अल्पकालिक ऋण लें या 6 महीने परिवार के खर्च कम करें?',
    prompt_ta: 'கரும்பு அறுவடைக்கு 12 மாதங்கள். 6 மாத வீட்டு செலவுக்கு மட்டுமே சேமிப்பு. இப்போது குறுகிய கால கடன் வாங்குவீர்களா அல்லது 6 மாதம் குடும்ப செலவை குறைப்பீர்களா?',
    left: { label: 'Take short-term loan', description: 'Cover costs but add debt burden.' },
    right: { label: 'Cut expenses for 6 months', description: 'Tough but debt-free until harvest.' },
    left_label_hi: 'अल्पकालिक ऋण लें', left_desc_hi: 'लागत पूरी करें लेकिन कर्ज़ का बोझ।',
    right_label_hi: '6 महीने खर्च कम करें', right_desc_hi: 'कठिन लेकिन फसल तक कर्ज़ मुक्त।',
    left_label_ta: 'குறுகிய கால கடன் வாங்கு', left_desc_ta: 'செலவு சமாளி ஆனால் கடன் சுமை.',
    right_label_ta: '6 மாதம் செலவை குறை', right_desc_ta: 'கஷ்டமானது ஆனால் அறுவடை வரை கடன் இல்லை.',
    effectsLeft:  { family: 10, crops: 0, finance: -20, resilience: -10 },
    effectsRight: { family: -15, crops: 5, finance: 10, resilience: 15 },
    narrator: 'elder',
    tags: ['sugarcane', 'cash_flow', 'sowing'],
    triggerDebtTrap: true,
  },
  {
    id: 'sugarcane_intercrop',
    seasonPhase: 'sowing',
    title: 'Intercropping with Sugarcane',
    title_hi: 'गन्ने के साथ अंतरफसल',
    title_ta: 'கரும்புடன் இடைப்பயிர்',
    prompt: 'In the first 4 months while sugarcane is young, you can grow garlic or onion as intercrop in the gaps. Extra income of ₹15,000–20,000 but needs more labour and water.',
    prompt_hi: 'पहले 4 महीनों में जब गन्ना छोटा होता है, आप अंतराल में लहसुन या प्याज़ अंतरफसल उगा सकते हैं। ₹15,000–20,000 अतिरिक्त आय लेकिन अधिक मज़दूरी और पानी चाहिए।',
    prompt_ta: 'முதல் 4 மாதங்களில் கரும்பு சிறியதாக இருக்கும்போது, இடைவெளிகளில் பூண்டு அல்லது வெங்காயம் இடைப்பயிராக வளர்க்கலாம். ₹15,000–20,000 கூடுதல் வருமானம் ஆனால் அதிக தொழிலாளர் மற்றும் நீர் தேவை.',
    left: { label: 'Skip intercrop, focus on cane', description: 'Less work, but miss extra income.' },
    right: { label: 'Grow garlic/onion intercrop', description: 'Extra ₹15,000–20,000 income in 4 months.' },
    left_label_hi: 'अंतरफसल छोड़ें, गन्ने पर ध्यान दें', left_desc_hi: 'कम काम, लेकिन अतिरिक्त आय चूक जाएं।',
    right_label_hi: 'लहसुन/प्याज़ अंतरफसल उगाएं', right_desc_hi: '4 महीनों में ₹15,000–20,000 अतिरिक्त आय।',
    left_label_ta: 'இடைப்பயிர் தவிர், கரும்பில் கவனம்', left_desc_ta: 'குறைந்த வேலை, ஆனால் கூடுதல் வருமானம் தவறும்.',
    right_label_ta: 'பூண்டு/வெங்காயம் இடைப்பயிர் வளர்', right_desc_ta: '4 மாதங்களில் ₹15,000–20,000 கூடுதல் வருமானம்.',
    effectsLeft:  { family: 0,  crops: 5,  finance: -5,  resilience: 5  },
    effectsRight: { family: 5,  crops: 10, finance: 20,  resilience: 10 },
    narrator: 'bank_mitr',
    tags: ['sugarcane', 'intercrop', 'sowing'],
  },
  {
    id: 'sugarcane_mill_delay',
    seasonPhase: 'harvest',
    title: 'Sugar Mill Payment Delay',
    title_hi: 'चीनी मिल भुगतान में देरी',
    title_ta: 'சர்க்கரை ஆலை கட்டண தாமதம்',
    prompt: 'The sugar mill accepted your cane but payment comes in 90 days. You need cash now for next season. A commission agent offers immediate cash at 8% deduction.',
    prompt_hi: 'चीनी मिल ने गन्ना स्वीकार किया लेकिन भुगतान 90 दिनों में आएगा। अगले सीज़न के लिए अभी नकद चाहिए। एक कमीशन एजेंट 8% कटौती पर तुरंत नकद देता है।',
    prompt_ta: 'சர்க்கரை ஆலை கரும்பை ஏற்றது ஆனால் 90 நாட்களில் கட்டணம். அடுத்த சீசனுக்கு இப்போதே பணம் தேவை. கமிஷன் முகவர் 8% கழிவில் உடனடி பணம் தருகிறார்.',
    left: { label: 'Take agent cash at 8% cut', description: 'Immediate but lose ₹1,600 per ₹20,000.' },
    right: { label: 'Wait 90 days for full payment', description: 'Full amount but delay next season prep.' },
    left_label_hi: '8% कटौती पर एजेंट से नकद लें', left_desc_hi: 'तुरंत लेकिन ₹20,000 पर ₹1,600 खोएं।',
    right_label_hi: 'पूरे भुगतान के लिए 90 दिन इंतज़ार करें', right_desc_hi: 'पूरी राशि लेकिन अगले सीज़न में देरी।',
    left_label_ta: '8% கழிவில் முகவரிடம் பணம் வாங்கு', left_desc_ta: 'உடனடி ஆனால் ₹20,000-க்கு ₹1,600 இழப்பு.',
    right_label_ta: 'முழு கட்டணத்திற்கு 90 நாட்கள் காத்திரு', right_desc_ta: 'முழு தொகை ஆனால் அடுத்த சீசன் தயாரிப்பில் தாமதம்.',
    effectsLeft:  { family: 5,  crops: 5,  finance: -15, resilience: -5  },
    effectsRight: { family: -5, crops: 0,  finance: 20,  resilience: 10  },
    narrator: 'bank_mitr',
    tags: ['sugarcane', 'mill_payment', 'harvest'],
  },
  {
    id: 'sugarcane_red_rot',
    seasonPhase: 'growing',
    title: 'Red Rot Disease in Sugarcane',
    title_hi: 'गन्ने में लाल सड़न रोग',
    title_ta: 'கரும்பில் சிவப்பு அழுகல் நோய்',
    prompt: 'You notice red discolouration inside some cane stalks — red rot disease. Infected plants must be uprooted and burned. Delay risks spreading to 60% of your field.',
    prompt_hi: 'आपको कुछ गन्ने के डंठलों के अंदर लाल रंग दिखता है — लाल सड़न रोग। संक्रमित पौधों को उखाड़कर जलाना होगा। देरी से 60% खेत में फैलने का जोखिम।',
    prompt_ta: 'சில கரும்பு தண்டுகளுக்குள் சிவப்பு நிறம் தெரிகிறது — சிவப்பு அழுகல் நோய். பாதிக்கப்பட்ட செடிகளை பிடுங்கி எரிக்க வேண்டும். தாமதம் 60% வயலுக்கு பரவும் ஆபத்து.',
    left: { label: 'Wait and monitor for a week', description: 'Risk disease spreading to entire field.' },
    right: { label: 'Uproot and burn infected plants now', description: 'Lose 10% crop but save the rest.' },
    left_label_hi: 'एक हफ्ते देखें और निगरानी करें', left_desc_hi: 'पूरे खेत में रोग फैलने का जोखिम।',
    right_label_hi: 'अभी संक्रमित पौधे उखाड़ें और जलाएं', right_desc_hi: '10% फसल खोएं लेकिन बाकी बचाएं।',
    left_label_ta: 'ஒரு வாரம் பார்த்து கண்காணி', left_desc_ta: 'முழு வயலுக்கும் நோய் பரவும் ஆபத்து.',
    right_label_ta: 'இப்போதே பாதிக்கப்பட்ட செடிகளை பிடுங்கி எரி', right_desc_ta: '10% பயிர் இழப்பு ஆனால் மீதியை காப்பாற்று.',
    effectsLeft:  { family: 0, crops: -35, finance: 5,   resilience: -15 },
    effectsRight: { family: 0, crops: 10,  finance: -5,  resilience: 20  },
    narrator: 'elder',
    tags: ['sugarcane', 'disease', 'growing'],
  },
  {
    id: 'sugarcane_drip_irrigation',
    seasonPhase: 'sowing',
    title: 'Drip Irrigation for Sugarcane',
    title_hi: 'गन्ने के लिए ड्रिप सिंचाई',
    title_ta: 'கரும்புக்கு சொட்டு நீர்ப்பாசனம்',
    prompt: 'Drip irrigation for sugarcane saves 40% water and increases yield by 20%. Setup cost is ₹40,000/acre but government subsidy covers 55% = ₹18,000 your share. Worth it?',
    prompt_hi: 'गन्ने के लिए ड्रिप सिंचाई 40% पानी बचाती है और उपज 20% बढ़ाती है। सेटअप लागत ₹40,000/एकड़ है लेकिन सरकारी सब्सिडी 55% = ₹18,000 आपका हिस्सा। क्या यह फायदेमंद है?',
    prompt_ta: 'கரும்புக்கு சொட்டு நீர்ப்பாசனம் 40% நீர் சேமிக்கும், மகசூல் 20% அதிகரிக்கும். அமைப்பு செலவு ₹40,000/ஏக்கர் ஆனால் அரசு மானியம் 55% = ₹18,000 உங்கள் பங்கு. மதிப்புள்ளதா?',
    left: { label: 'Skip drip, use flood irrigation', description: 'No upfront cost but high water use.' },
    right: { label: 'Install drip with subsidy', description: '₹18,000 now, saves water and boosts yield for years.' },
    left_label_hi: 'ड्रिप छोड़ें, बाढ़ सिंचाई उपयोग करें', left_desc_hi: 'कोई अग्रिम लागत नहीं लेकिन अधिक पानी उपयोग।',
    right_label_hi: 'सब्सिडी के साथ ड्रिप लगाएं', right_desc_hi: 'अभी ₹18,000, सालों तक पानी बचाएं और उपज बढ़ाएं।',
    left_label_ta: 'சொட்டு தவிர், வெள்ள நீர்ப்பாசனம்', left_desc_ta: 'முன்பணம் இல்லை ஆனால் அதிக நீர் பயன்பாடு.',
    right_label_ta: 'மானியத்துடன் சொட்டு நீர்ப்பாசனம் நிறுவு', right_desc_ta: 'இப்போது ₹18,000, ஆண்டுகளாக நீர் சேமிப்பு மற்றும் மகசூல் அதிகரிப்பு.',
    effectsLeft:  { family: 0, crops: -5,  finance: 5,  resilience: -15 },
    effectsRight: { family: 0, crops: 20,  finance: -10, resilience: 25 },
    narrator: 'bank_mitr',
    tags: ['sugarcane', 'irrigation', 'subsidy', 'sowing'],
  },
]

// ─── POTATO ───────────────────────────────────────────────────────
export const potatoCards = [
  {
    id: 'potato_seed_selection',
    seasonPhase: 'pre_sowing',
    title: 'Potato Seed Variety',
    title_hi: 'आलू बीज किस्म',
    title_ta: 'உருளைக்கிழங்கு விதை வகை',
    prompt: 'Kufri Jyoti (traditional) costs ₹18/kg, you know it well. Kufri Pukhraj (new variety) costs ₹28/kg but matures 20 days earlier and resists late blight better.',
    prompt_hi: 'कुफरी ज्योति (पारंपरिक) ₹18/किलो, आप इसे अच्छी तरह जानते हैं। कुफरी पुखराज (नई किस्म) ₹28/किलो लेकिन 20 दिन पहले पकती है और लेट ब्लाइट से बेहतर बचाव करती है।',
    prompt_ta: 'குஃப்ரி ஜ்யோதி (பாரம்பரிய) ₹18/கிலோ, நன்கு தெரியும். குஃப்ரி புகராஜ் (புதிய வகை) ₹28/கிலோ ஆனால் 20 நாட்கள் முன்னதாக முதிர்ந்து லேட் ப்ளைட்டை சிறப்பாக எதிர்க்கும்.',
    left: { label: 'Kufri Jyoti — familiar, cheaper', description: 'Lower cost, known performance.' },
    right: { label: 'Kufri Pukhraj — new, disease-resistant', description: 'Higher cost but earlier harvest and blight resistance.' },
    left_label_hi: 'कुफरी ज्योति — परिचित, सस्ता', left_desc_hi: 'कम लागत, जानी-पहचानी उपज।',
    right_label_hi: 'कुफरी पुखराज — नया, रोग-प्रतिरोधी', right_desc_hi: 'अधिक लागत लेकिन जल्दी कटाई और ब्लाइट प्रतिरोध।',
    left_label_ta: 'குஃப்ரி ஜ்யோதி — பரிச்சயமான, மலிவான', left_desc_ta: 'குறைந்த செலவு, தெரிந்த செயல்திறன்.',
    right_label_ta: 'குஃப்ரி புகராஜ் — புதிய, நோய்-எதிர்ப்பு', right_desc_ta: 'அதிக செலவு ஆனால் முன்னதாக அறுவடை மற்றும் ப்ளைட் எதிர்ப்பு.',
    effectsLeft:  { family: 0, crops: -5,  finance: 10, resilience: -10 },
    effectsRight: { family: 0, crops: 20,  finance: -10, resilience: 15 },
    narrator: 'bank_mitr',
    tags: ['potato', 'seeds', 'pre_sowing'],
  },
  {
    id: 'potato_planting_depth',
    seasonPhase: 'sowing',
    title: 'Potato Planting Depth',
    title_hi: 'आलू रोपण गहराई',
    title_ta: 'உருளைக்கிழங்கு நடவு ஆழம்',
    prompt: 'Recommended planting depth for potato is 5–7cm. Your labourer suggests 10cm saying "deeper is better." Shallow planting risks greening; deep planting delays emergence.',
    prompt_hi: 'आलू के लिए अनुशंसित रोपण गहराई 5–7 सेमी है। आपका मज़दूर 10 सेमी सुझाता है कहते हुए "गहरा बेहतर है।" उथली रोपाई से हरापन का जोखिम; गहरी रोपाई से उगने में देरी।',
    prompt_ta: 'உருளைக்கிழங்குக்கு பரிந்துரைக்கப்பட்ட நடவு ஆழம் 5–7செமீ. தொழிலாளர் 10செமீ பரிந்துரைக்கிறார் "ஆழமானது சிறந்தது" என்று. ஆழமற்ற நடவு பச்சை நிறம் ஆபத்து; ஆழமான நடவு முளைப்பு தாமதம்.',
    left: { label: 'Plant at 10cm as labourer says', description: 'Delayed emergence, lower early yield.' },
    right: { label: 'Plant at 5–7cm as recommended', description: 'Correct depth, optimal emergence.' },
    left_label_hi: 'मज़दूर के अनुसार 10 सेमी पर लगाएं', left_desc_hi: 'उगने में देरी, शुरुआती उपज कम।',
    right_label_hi: 'अनुशंसित 5–7 सेमी पर लगाएं', right_desc_hi: 'सही गहराई, इष्टतम उगाव।',
    left_label_ta: 'தொழிலாளர் சொல்படி 10செமீ நடவு', left_desc_ta: 'முளைப்பு தாமதம், ஆரம்ப மகசூல் குறைவு.',
    right_label_ta: 'பரிந்துரைக்கப்பட்ட 5–7செமீ நடவு', right_desc_ta: 'சரியான ஆழம், சிறந்த முளைப்பு.',
    effectsLeft:  { family: 0, crops: -10, finance: 0,  resilience: -5  },
    effectsRight: { family: 0, crops: 15,  finance: -5, resilience: 10  },
    narrator: 'elder',
    tags: ['potato', 'planting', 'sowing'],
  },
  {
    id: 'potato_fungus_attack',
    seasonPhase: 'growing',
    title: 'Late Blight Emergency',
    title_hi: 'लेट ब्लाइट आपातकाल',
    title_ta: 'லேட் ப்ளைட் அவசரநிலை',
    prompt: 'Brown lesions on potato leaves — early late blight. Untreated, it destroys 80% of crop in 2 weeks. Mancozeb spray costs ₹1,500/acre. Your neighbour says wait 3 days.',
    prompt_hi: 'आलू की पत्तियों पर भूरे धब्बे — शुरुआती लेट ब्लाइट। अगर इलाज न हो तो 2 हफ्ते में 80% फसल नष्ट। मैंकोज़ेब स्प्रे ₹1,500/एकड़। पड़ोसी कहता है 3 दिन इंतज़ार करें।',
    prompt_ta: 'உருளைக்கிழங்கு இலைகளில் பழுப்பு புண்கள் — ஆரம்ப லேட் ப்ளைட். சிகிச்சை இல்லாவிட்டால் 2 வாரங்களில் 80% பயிர் அழியும். மேன்கோசெப் தெளிப்பு ₹1,500/ஏக்கர். அண்டை வீட்டார் 3 நாட்கள் காத்திரு என்கிறார்.',
    left: { label: 'Wait 3 days, monitor', description: 'Risk total crop loss in humid weather.' },
    right: { label: 'Spray Mancozeb immediately', description: '₹1,500 now saves 80% of your crop.' },
    left_label_hi: '3 दिन इंतज़ार करें, निगरानी करें', left_desc_hi: 'नम मौसम में पूरी फसल हानि का जोखिम।',
    right_label_hi: 'तुरंत मैंकोज़ेब स्प्रे करें', right_desc_hi: 'अभी ₹1,500 आपकी 80% फसल बचाता है।',
    left_label_ta: '3 நாட்கள் காத்திரு, கண்காணி', left_desc_ta: 'ஈரமான வானிலையில் முழு பயிர் இழப்பு ஆபத்து.',
    right_label_ta: 'உடனே மேன்கோசெப் தெளி', right_desc_ta: 'இப்போது ₹1,500 உங்கள் 80% பயிரை காப்பாற்றும்.',
    effectsLeft:  { family: 0, crops: -35, finance: 5,   resilience: -15 },
    effectsRight: { family: 0, crops: 20,  finance: -10, resilience: 15  },
    narrator: 'elder',
    tags: ['potato', 'disease', 'growing'],
  },
  {
    id: 'potato_earthing_up',
    seasonPhase: 'growing',
    title: 'Earthing Up Potato',
    title_hi: 'आलू की मिट्टी चढ़ाना',
    title_ta: 'உருளைக்கிழங்கு மண் அணைத்தல்',
    prompt: 'Earthing up (hilling) at 30 days after planting prevents greening and increases tuber formation. It costs ₹800/acre in labour. Skip it to save money?',
    prompt_hi: 'रोपाई के 30 दिन बाद मिट्टी चढ़ाना (हिलिंग) हरापन रोकता है और कंद निर्माण बढ़ाता है। इसमें ₹800/एकड़ मज़दूरी लगती है। पैसे बचाने के लिए छोड़ें?',
    prompt_ta: 'நடவுக்கு 30 நாட்கள் பிறகு மண் அணைத்தல் பச்சை நிறம் தடுக்கும், கிழங்கு உருவாக்கம் அதிகரிக்கும். ₹800/ஏக்கர் தொழிலாளர் செலவு. பணம் சேமிக்க தவிர்க்கவா?',
    left: { label: 'Skip earthing up, save ₹800', description: 'Risk greening and lower tuber yield.' },
    right: { label: 'Do earthing up on time', description: '₹800 investment, better yield and quality.' },
    left_label_hi: 'मिट्टी चढ़ाना छोड़ें, ₹800 बचाएं', left_desc_hi: 'हरापन और कम कंद उपज का जोखिम।',
    right_label_hi: 'समय पर मिट्टी चढ़ाएं', right_desc_hi: '₹800 निवेश, बेहतर उपज और गुणवत्ता।',
    left_label_ta: 'மண் அணைத்தல் தவிர், ₹800 சேமி', left_desc_ta: 'பச்சை நிறம் மற்றும் குறைந்த கிழங்கு மகசூல் ஆபத்து.',
    right_label_ta: 'சரியான நேரத்தில் மண் அணைத்தல் செய்', right_desc_ta: '₹800 முதலீடு, சிறந்த மகசூல் மற்றும் தரம்.',
    effectsLeft:  { family: 0, crops: -15, finance: 5,  resilience: -5  },
    effectsRight: { family: 0, crops: 15,  finance: -5, resilience: 10  },
    narrator: 'bank_mitr',
    tags: ['potato', 'cultivation', 'growing'],
  },
  {
    id: 'potato_cold_storage',
    seasonPhase: 'harvest',
    title: 'Cold Storage Decision',
    title_hi: 'कोल्ड स्टोरेज निर्णय',
    title_ta: 'குளிர் சேமிப்பு முடிவு',
    prompt: 'Potato prices crash at harvest to ₹4/kg. Cold storage costs ₹200/tonne for 3 months. Prices usually rise to ₹9–12/kg by summer. But storage space is limited.',
    prompt_hi: 'कटाई के समय आलू की कीमत ₹4/किलो तक गिर जाती है। कोल्ड स्टोरेज 3 महीने के लिए ₹200/टन है। गर्मियों तक कीमतें ₹9–12/किलो तक बढ़ जाती हैं। लेकिन भंडारण स्थान सीमित है।',
    prompt_ta: 'அறுவடையில் உருளைக்கிழங்கு விலை ₹4/கிலோவாக சரிகிறது. குளிர் சேமிப்பு 3 மாதங்களுக்கு ₹200/டன். கோடையில் விலை ₹9–12/கிலோவாக உயரும். ஆனால் சேமிப்பு இடம் குறைவு.',
    left: { label: 'Sell now at ₹4/kg', description: 'Certain money, no storage risk.' },
    right: { label: 'Store and sell in summer', description: 'Potential 3x profit but storage cost and risk.' },
    left_label_hi: 'अभी ₹4/किलो पर बेचें', left_desc_hi: 'निश्चित पैसा, भंडारण जोखिम नहीं।',
    right_label_hi: 'रखें और गर्मियों में बेचें', right_desc_hi: '3 गुना मुनाफे की संभावना लेकिन भंडारण लागत और जोखिम।',
    left_label_ta: 'இப்போது ₹4/கிலோவில் விற்று', left_desc_ta: 'நிச்சயமான பணம், சேமிப்பு ஆபத்து இல்லை.',
    right_label_ta: 'சேமி, கோடையில் விற்று', right_desc_ta: '3 மடங்கு லாப வாய்ப்பு ஆனால் சேமிப்பு செலவு மற்றும் ஆபத்து.',
    effectsLeft:  { family: 0, crops: 0,  finance: -5,  resilience: -5  },
    effectsRight: { family: 0, crops: 5,  finance: 20,  resilience: -10 },
    narrator: 'self',
    tags: ['potato', 'cold_storage', 'harvest'],
  },
  {
    id: 'potato_chips_contract',
    seasonPhase: 'harvest',
    title: 'Chips Factory Contract',
    title_hi: 'चिप्स फैक्ट्री अनुबंध',
    title_ta: 'சிப்ஸ் தொழிற்சாலை ஒப்பந்தம்',
    prompt: 'A chips factory offers a contract: buy all your potato at ₹7/kg guaranteed, but only if you grow Chipsona variety next season. Current market is ₹4–12/kg (unpredictable).',
    prompt_hi: 'एक चिप्स फैक्ट्री अनुबंध देती है: ₹7/किलो पर सारा आलू खरीदेगी, लेकिन केवल तभी जब आप अगले सीज़न चिप्सोना किस्म उगाएं। वर्तमान बाज़ार ₹4–12/किलो (अनिश्चित) है।',
    prompt_ta: 'சிப்ஸ் தொழிற்சாலை ஒப்பந்தம் தருகிறது: ₹7/கிலோவில் உங்கள் உருளைக்கிழங்கு முழுவதும் வாங்கும், ஆனால் அடுத்த சீசன் சிப்சோனா வகை வளர்க்க வேண்டும். தற்போதைய சந்தை ₹4–12/கிலோ (கணிக்க முடியாதது).',
    left: { label: 'Reject contract, sell freely', description: 'Market risk but potential for ₹12/kg.' },
    right: { label: 'Accept contract at ₹7/kg', description: 'Guaranteed price, no market risk.' },
    left_label_hi: 'अनुबंध अस्वीकार करें, स्वतंत्र रूप से बेचें', left_desc_hi: 'बाज़ार जोखिम लेकिन ₹12/किलो की संभावना।',
    right_label_hi: '₹7/किलो पर अनुबंध स्वीकार करें', right_desc_hi: 'गारंटीड कीमत, बाज़ार जोखिम नहीं।',
    left_label_ta: 'ஒப்பந்தம் நிராகரி, சுதந்திரமாக விற்று', left_desc_ta: 'சந்தை ஆபத்து ஆனால் ₹12/கிலோ வாய்ப்பு.',
    right_label_ta: '₹7/கிலோவில் ஒப்பந்தம் ஏற்று', right_desc_ta: 'உத்தரவாத விலை, சந்தை ஆபத்து இல்லை.',
    effectsLeft:  { family: 0, crops: 5,  finance: 10, resilience: -10 },
    effectsRight: { family: 5, crops: 10, finance: 15, resilience: 15  },
    narrator: 'bank_mitr',
    tags: ['potato', 'contract_farming', 'harvest'],
  },
  {
    id: 'potato_haulm_killing',
    seasonPhase: 'harvest',
    title: 'Haulm Killing Before Harvest',
    title_hi: 'कटाई से पहले पत्ती नष्ट करना',
    title_ta: 'அறுவடைக்கு முன் தண்டு அழிப்பு',
    prompt: 'Killing potato haulm (tops) 2 weeks before harvest hardens the skin, reduces bruising, and improves storage life. Chemical desiccant costs ₹600/acre. Skip it to save cost?',
    prompt_hi: 'कटाई से 2 हफ्ते पहले आलू की पत्तियां नष्ट करने से छिलका सख्त होता है, चोट कम लगती है और भंडारण जीवन बढ़ता है। रासायनिक डेसिकेंट ₹600/एकड़ है। लागत बचाने के लिए छोड़ें?',
    prompt_ta: 'அறுவடைக்கு 2 வாரங்கள் முன் உருளைக்கிழங்கு தண்டுகளை அழிப்பது தோலை கடினமாக்கும், காயம் குறைக்கும், சேமிப்பு ஆயுளை அதிகரிக்கும். ரசாயன டெசிகேண்ட் ₹600/ஏக்கர். செலவு சேமிக்க தவிர்க்கவா?',
    left: { label: 'Skip haulm killing, save ₹600', description: 'Softer skin, more bruising, shorter storage life.' },
    right: { label: 'Kill haulm 2 weeks before harvest', description: 'Better quality, longer storage, higher price.' },
    left_label_hi: 'पत्ती नष्ट करना छोड़ें, ₹600 बचाएं', left_desc_hi: 'नरम छिलका, अधिक चोट, कम भंडारण जीवन।',
    right_label_hi: 'कटाई से 2 हफ्ते पहले पत्तियां नष्ट करें', right_desc_hi: 'बेहतर गुणवत्ता, लंबा भंडारण, अधिक कीमत।',
    left_label_ta: 'தண்டு அழிப்பு தவிர், ₹600 சேமி', left_desc_ta: 'மென்மையான தோல், அதிக காயம், குறைந்த சேமிப்பு ஆயுள்.',
    right_label_ta: 'அறுவடைக்கு 2 வாரங்கள் முன் தண்டு அழி', right_desc_ta: 'சிறந்த தரம், நீண்ட சேமிப்பு, அதிக விலை.',
    effectsLeft:  { family: 0, crops: -10, finance: 5,  resilience: -10 },
    effectsRight: { family: 0, crops: 15,  finance: -5, resilience: 15  },
    narrator: 'elder',
    tags: ['potato', 'harvest', 'quality'],
  },
]

// ─── Map crop key → cards ─────────────────────────────────────────
export const CROP_CARD_MAP = {
  wheat:     wheatCards,
  paddy:     paddyCards,
  sugarcane: sugarcaneCards,
  potato:    potatoCards,
}

/**
 * Build a personalized deck.
 *
 * When crops are selected:
 *   - Include ALL cards for each selected crop
 *   - Include ONLY universal base cards (fraud, health, savings, govt schemes)
 *   - Exclude generic crop cards from base deck (mandi_low_price, monsoon_delay, etc.)
 *
 * @param {string[]} selectedCrops  e.g. ['wheat','potato']
 * @param {import('./faislaDeck').FaislaCard[]} baseDeck
 * @returns {import('./faislaDeck').FaislaCard[]}
 */
export function buildPersonalizedDeck(selectedCrops, baseDeck) {
  // Filter base deck to only truly universal cards
  const universalCards = baseDeck.filter((card) =>
    card.tags?.some((tag) => UNIVERSAL_TAGS.includes(tag))
  )

  // Get all crop-specific cards for selected crops
  const cropCards = selectedCrops.flatMap((c) => CROP_CARD_MAP[c] ?? [])

  const combined = [...cropCards, ...universalCards]

  // Shuffle
  for (let i = combined.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[combined[i], combined[j]] = [combined[j], combined[i]]
  }
  return combined
}
